[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10 

#opacity = 0.75
#blur = true

startup_mode = "Maximized"
decorations = "None"
option_as_alt = "OnlyLeft"

[cursor]
style = { shape = "Block", blinking = "Never" }

[font]
normal.family = "Iosevka Nerd Font"
size = 25

[colors.primary]
background = "#282828"
foreground = "#f2e9e1"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = '#1a1a1b'
red = '#cc241d'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#f2e9e1'
