format = "$directory$git_branch$character"
add_newline = false

[line_break]
disabled = true

[directory]
style = "fg:#ebdbb2"
truncate_to_repo = false
truncation_length = 0

[git_branch]
format = "[git:\\(](fg:#83a598)[$branch](fg:#e3412f)[\\)](fg:#83a598) "
style = "fg:#d8a657"

[character]
success_symbol = "[\\$](fg:#83a598)"
error_symbol = "[\\$](fg:83a598)"

[cmd_duration]
disabled = true

[package]
disabled = true

[git_status]
disabled = true

[rust]
disabled = true
