format = "$directory$character"
add_newline = false

[line_break]
disabled = true

[directory]
style = "fg:#7daea3"
truncate_to_repo = false

[character]
success_symbol = "[\\$](fg:white) "
error_symbol = "[\\$](fg:white) "

[cmd_duration]
disabled = true

[package]
disabled = true

[git_branch]
disabled = true

[git_status]
disabled = true

[rust]
disabled = true
