format = "$directory$git_branch$character"
add_newline = false

[line_break]
disabled = true

[directory]
style = "fg:#7daea3"
truncate_to_repo = false
truncation_length = 0

[git_branch]
format = "[git:\\(](fg:#c4dfee)[$branch](fg:#de7f9c)[\\)](fg:#c4dfee) "
style = "fg:#d8a657"

[character]
success_symbol = "[\\$](fg:#c4dfee) "
error_symbol = "[\\$](fg:c4dfee) "

[cmd_duration]
disabled = true

[package]
disabled = true

[git_status]
disabled = true

[rust]
disabled = true
