#!/bin/bash
source "$CONFIG_DIR/colors.sh" 
PLUGIN_DIR="$CONFIG_DIR/plugins"

sketchybar --bar position=top height=40 blur_radius=30 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=1
  padding_right=1
  icon.font="JetBrainsMono Nerd Font:Bold:16"
  label.font="JetBrainsMono Nerd Font:Bold:16.0"
  icon.color=$BAR_COLOR
  label.color=$BAR_COLOR
  background.color=$ACCENT_COLOR      \
  background.corner_radius=2            \
  background.height=24                  \
  icon.padding_left=5
  icon.padding_right=5
  label.padding_left=5
  label.padding_right=5
)
sketchybar --default "${default[@]}"

sketchybar --add item calendar right \
           --set calendar icon.drawing=off \
                          padding_left=5 \
                          update_freq=30 \
                          script="$PLUGIN_DIR/calendar.sh" \

sketchybar --add item battery right \
           --set battery update_freq=120 \
                         script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

SPACE_SIDS=(1 2 3 4)

sketchybar --add event aerospace_workspace_change

for sid in "${SPACE_SIDS[@]}"
do
  sketchybar --add item space.$sid left \
             --set space.$sid \
                          icon="$sid" \
                          icon.font="JetBrainsMono Nerd Font:Bold:16.0" \
                          label.drawing=off \
                          click_script="aerospace workspace $sid" \
                          script="$PLUGIN_DIR/space.sh $sid" \
             --subscribe space.$sid aerospace_workspace_change
done

sketchybar --add item space_separator left \
           --set space_separator icon.drawing=off \
                                 label.drawing=off \
                                 background.drawing=off

sketchybar --update
